/**
 * Data Validation Schemas
 *
 * Comprehensive Zod schemas for validating data at application boundaries.
 *
 * @see docs/plans/ui/04-data-requirements.md
 */

// ============================================
// Turso Database Schemas
// ============================================

export {
  type AgentOutputInsert,
  AgentOutputInsertSchema,
  AgentTypeEnum,
  type AlertInsert,
  AlertInsertSchema,
  AlertSeverityType,
  type AlertUpdate,
  AlertUpdateSchema,
  type CandleInsert,
  CandleInsertSchema,
  ConfidenceSchema,
  type CycleLogInsert,
  CycleLogInsertSchema,
  type CycleLogUpdate,
  CycleLogUpdateSchema,
  CyclePhase,
  DatetimeSchema,
  DecimalPercentSchema,
  type DecisionInsert,
  DecisionInsertSchema,
  DecisionStatus,
  type DecisionUpdate,
  DecisionUpdateSchema,
  Environment,
  EquityTickerSchema,
  type IndicatorInsert,
  IndicatorInsertSchema,
  MarketRegime,
  type MarketSnapshotInsert,
  MarketSnapshotInsertSchema,
  MoneySchema,
  type OptionChainInsert,
  OptionChainInsertSchema,
  OptionTypeEnum,
  type OrderInsert,
  OrderInsertSchema,
  OrderSideType,
  OrderStatusType,
  OrderTypeType,
  type OrderUpdate,
  OrderUpdateSchema,
  PercentageSchema,
  type PortfolioSnapshotInsert,
  PortfolioSnapshotInsertSchema,
  PositionDirection,
  type PositionInsert,
  PositionInsertSchema,
  type PositionUpdate,
  PositionUpdateSchema,
  type RegimeInsert,
  RegimeInsertSchema,
  SizeUnitType,
  TickerSymbolSchema,
  Timeframe,
  TradingAction,
  UuidSchema,
} from "./turso.js";

// ============================================
// HelixDB Schemas
// ============================================

export {
  type CitationNode,
  CitationNodeSchema,
  CitationSource,
  type CitesEdge,
  CitesEdgeSchema,
  type DecisionNode,
  DecisionNodeSchema,
  EMBEDDING_DIMENSION,
  EmbeddingSchema,
  type InvalidatesEdge,
  InvalidatesEdgeSchema,
  type MarketContextNode,
  MarketContextNodeSchema,
  type MemoryNode,
  type MemoryNodeCreate,
  MemoryNodeCreateSchema,
  MemoryNodeSchema,
  type OccurredInEdge,
  OccurredInEdgeSchema,
  type ReferencesEdge,
  ReferencesEdgeSchema,
  type SupportsEdge,
  SupportsEdgeSchema,
  type ThesisNode,
  ThesisNodeSchema,
  ThesisState,
  type ThesisUpdate,
  ThesisUpdateSchema,
  type TransitionsEdge,
  TransitionsEdgeSchema,
  type VectorSearchQuery,
  VectorSearchQuerySchema,
  type VectorSearchResult,
  VectorSearchResultSchema,
  validateEmbedding,
  validateThesisTransition,
} from "./helix.js";

// ============================================
// Validation Utilities
// ============================================

export {
  type BatchValidationResult,
  coerceBool,
  coerceDate,
  coerceInt,
  containsSqlInjection,
  createTypeGuard,
  formatValidationError,
  formatZodIssue,
  getErrorMessages,
  type ParseResult,
  parseWithDefaults,
  partialExcept,
  safeParse,
  safeString,
  safeTickerSymbol,
  sanitizeString,
  type ValidationError,
  type ValidationFieldError,
  validateBatch,
  validated,
  validatedSafe,
  withSoftDelete,
  withTimestamps,
} from "./validation.js";

// ============================================
// DecisionPlan Schemas (Protobuf mirrors)
// ============================================

export {
  type Action,
  ActionSchema,
  type Decision,
  type DecisionPlan,
  DecisionPlanSchema,
  type DecisionPlanValidationResult,
  DecisionPlanValidationResultSchema,
  DecisionSchema,
  type Direction,
  DirectionSchema,
  type Environment as DecisionEnvironment,
  EnvironmentSchema as DecisionEnvironmentSchema,
  type ExecutionParams,
  ExecutionParamsSchema,
  type ExecutionTactic,
  ExecutionTacticSchema,
  type Instrument,
  InstrumentSchema,
  type InstrumentType,
  InstrumentTypeSchema,
  type ISO8601Timestamp,
  ISO8601TimestampSchema,
  type OptionContract,
  OptionContractSchema,
  type OptionType as DecisionOptionType,
  OptionTypeSchema as DecisionOptionTypeSchema,
  type OrderPlan,
  OrderPlanSchema,
  type OrderType as DecisionOrderType,
  OrderTypeSchema as DecisionOrderTypeSchema,
  type References,
  ReferencesSchema,
  type Regime,
  RegimeSchema,
  type RiskDenomination,
  RiskDenominationSchema,
  type RiskLevels,
  RiskLevelsSchema,
  type RiskValidationResult,
  RiskValidationResultSchema,
  type Size,
  SizeSchema,
  type SizeUnit,
  SizeUnitSchema,
  type StrategyFamily,
  StrategyFamilySchema,
  type TimeInForce,
  TimeInForceSchema,
  validateDecisionPlan,
  validateRiskReward,
} from "./decision-plan.js";

// ============================================
// Expiration Handling Schemas
// ============================================

export {
  checkPinRisk,
  classifyMoneyness,
  DEFAULT_EXPIRATION_POLICY,
  EXPIRATION_CHECKPOINT_TIMES,
  ExpirationAction,
  ExpirationCheckpoint,
  type ExpirationEvaluation,
  ExpirationEvaluationSchema,
  type ExpirationPolicyConfig,
  ExpirationPolicyConfig as ExpirationPolicyConfigSchema,
  ExpirationReason,
  type ExpiringPosition,
  ExpiringPositionSchema,
  getCurrentCheckpoint,
  getMinimumDTE,
  getPinRiskThreshold,
  isPastCheckpoint,
  type MinimumDTEConfig,
  MinimumDTEConfig as MinimumDTEConfigSchema,
  Moneyness,
  type PinRiskConfig,
  PinRiskConfig as PinRiskConfigSchema,
  PositionTypeForDTE,
  parseETTimeToMinutes,
  shouldLetExpireWorthless,
} from "./expiration.js";
