// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.
//
// Arrow Flight protocol definition (simplified for TypeScript client)

// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts"
// @generated from file arrow/flight/protocol/flight.proto (package arrow.flight.protocol, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { MethodKind } from "@bufbuild/protobuf";
import {
  Action,
  ActionType,
  Criteria,
  Empty,
  FlightData,
  FlightDescriptor,
  FlightInfo,
  HandshakeRequest,
  HandshakeResponse,
  PollInfo,
  PutResult,
  Result,
  SchemaResult,
  Ticket,
} from "./flight_pb.js";

/**
 * A flight service is an endpoint for retrieving or storing Arrow data.
 *
 * @generated from service arrow.flight.protocol.FlightService
 */
export const FlightService = {
  typeName: "arrow.flight.protocol.FlightService",
  methods: {
    /**
     * Handshake between client and server. Depending on the server, the
     * handshake may be required to determine the token that should be used for
     * future operations.
     *
     * @generated from rpc arrow.flight.protocol.FlightService.Handshake
     */
    handshake: {
      name: "Handshake",
      I: HandshakeRequest,
      O: HandshakeResponse,
      kind: MethodKind.BiDiStreaming,
    },
    /**
     * Get a list of available streams given a particular criteria.
     *
     * @generated from rpc arrow.flight.protocol.FlightService.ListFlights
     */
    listFlights: {
      name: "ListFlights",
      I: Criteria,
      O: FlightInfo,
      kind: MethodKind.ServerStreaming,
    },
    /**
     * For a given FlightDescriptor, get information about how the flight can be
     * consumed.
     *
     * @generated from rpc arrow.flight.protocol.FlightService.GetFlightInfo
     */
    getFlightInfo: {
      name: "GetFlightInfo",
      I: FlightDescriptor,
      O: FlightInfo,
      kind: MethodKind.Unary,
    },
    /**
     * For a given FlightDescriptor, start a query and get information
     * to poll its execution status.
     *
     * @generated from rpc arrow.flight.protocol.FlightService.PollFlightInfo
     */
    pollFlightInfo: {
      name: "PollFlightInfo",
      I: FlightDescriptor,
      O: PollInfo,
      kind: MethodKind.Unary,
    },
    /**
     * For a given FlightDescriptor, get the Schema as described in Schema.fbs::Schema.
     *
     * @generated from rpc arrow.flight.protocol.FlightService.GetSchema
     */
    getSchema: {
      name: "GetSchema",
      I: FlightDescriptor,
      O: SchemaResult,
      kind: MethodKind.Unary,
    },
    /**
     * Retrieve a single stream associated with a particular descriptor
     * associated with the referenced ticket.
     *
     * @generated from rpc arrow.flight.protocol.FlightService.DoGet
     */
    doGet: {
      name: "DoGet",
      I: Ticket,
      O: FlightData,
      kind: MethodKind.ServerStreaming,
    },
    /**
     * Push a stream to the flight service associated with a particular
     * flight stream.
     *
     * @generated from rpc arrow.flight.protocol.FlightService.DoPut
     */
    doPut: {
      name: "DoPut",
      I: FlightData,
      O: PutResult,
      kind: MethodKind.BiDiStreaming,
    },
    /**
     * Open a bidirectional data channel for a given descriptor.
     *
     * @generated from rpc arrow.flight.protocol.FlightService.DoExchange
     */
    doExchange: {
      name: "DoExchange",
      I: FlightData,
      O: FlightData,
      kind: MethodKind.BiDiStreaming,
    },
    /**
     * Flight services can support an arbitrary number of simple actions in
     * addition to the possible ListFlights, GetFlightInfo, DoGet, DoPut
     * operations that are potentially available.
     *
     * @generated from rpc arrow.flight.protocol.FlightService.DoAction
     */
    doAction: {
      name: "DoAction",
      I: Action,
      O: Result,
      kind: MethodKind.ServerStreaming,
    },
    /**
     * A flight service exposes all of the available action types that it has
     * along with descriptions.
     *
     * @generated from rpc arrow.flight.protocol.FlightService.ListActions
     */
    listActions: {
      name: "ListActions",
      I: Empty,
      O: ActionType,
      kind: MethodKind.ServerStreaming,
    },
  },
} as const;
