/**
 * Data Provider Clients
 *
 * API clients for market data providers.
 */

// Alpaca Markets (unified market data provider)
export {
	type AlpacaBar,
	AlpacaBarSchema,
	type AlpacaClientConfig,
	type AlpacaCorporateActionDividend,
	AlpacaCorporateActionDividendSchema,
	type AlpacaCorporateActionSplit,
	AlpacaCorporateActionSplitSchema,
	AlpacaMarketDataClient,
	type AlpacaNewsArticle,
	AlpacaNewsArticleSchema,
	type AlpacaOptionContract,
	AlpacaOptionContractSchema,
	type AlpacaOptionGreeks,
	AlpacaOptionGreeksSchema,
	type AlpacaOptionSnapshot,
	AlpacaOptionSnapshotSchema,
	type AlpacaQuote,
	AlpacaQuoteSchema,
	type AlpacaSnapshot,
	AlpacaSnapshotSchema,
	type AlpacaTimeframe,
	type AlpacaTrade,
	AlpacaTradeSchema,
	createAlpacaClientFromEnv,
	isAlpacaConfigured,
	type OptionContractParams,
	type TradingEnvironment,
} from "./alpaca";
// Alpaca Screener (market movers, most actives)
export {
	AlpacaScreenerClient,
	type AlpacaScreenerConfig,
	createAlpacaScreenerFromEnv,
	isAlpacaScreenerConfigured,
	type MostActiveStock,
	MostActiveStockSchema,
	type MostActivesBy,
	type MostActivesResponse,
	MostActivesResponseSchema,
	type Mover,
	MoverSchema,
	type MoversResponse,
	MoversResponseSchema,
} from "./alpaca-screener";
// Alpaca WebSocket (real-time streaming)
export {
	AlpacaConnectionState,
	AlpacaWebSocketClient,
	type AlpacaWebSocketConfig,
	type AlpacaWsBarMessage,
	AlpacaWsBarMessageSchema,
	type AlpacaWsErrorMessage,
	AlpacaWsErrorMessageSchema,
	type AlpacaWsEvent,
	type AlpacaWsEventHandler,
	type AlpacaWsFeed,
	type AlpacaWsMarket,
	type AlpacaWsMessage,
	type AlpacaWsNewsMessage,
	AlpacaWsNewsMessageSchema,
	type AlpacaWsQuoteMessage,
	AlpacaWsQuoteMessageSchema,
	type AlpacaWsStatusMessage,
	AlpacaWsStatusMessageSchema,
	type AlpacaWsSubscriptionMessage,
	AlpacaWsSubscriptionMessageSchema,
	type AlpacaWsSuccessMessage,
	AlpacaWsSuccessMessageSchema,
	type AlpacaWsTradeMessage,
	AlpacaWsTradeMessageSchema,
	createAlpacaNewsClientFromEnv,
	createAlpacaOptionsClientFromEnv,
	createAlpacaStocksClientFromEnv,
	createAlpacaWebSocketClientFromEnv,
} from "./alpaca-websocket";
// Alpha Vantage
export {
	ALPHA_VANTAGE_RATE_LIMITS,
	AlphaVantageClient,
	type AlphaVantageClientConfig,
	createAlphaVantageClientFromEnv,
	type EconomicDataPoint,
	EconomicDataPointSchema,
	type EconomicIndicatorResponse,
	EconomicIndicatorResponseSchema,
	type EconomicIndicatorType,
	type EconomicInterval,
	type FederalFundsRateResponse,
	FederalFundsRateResponseSchema,
	INDICATOR_METADATA,
	type IndicatorMetadata,
	type TreasuryMaturity,
	type TreasuryYieldResponse,
	TreasuryYieldResponseSchema,
} from "./alphavantage";
