/**
 * Data Provider Clients
 *
 * API clients for market data providers.
 */

// Alpaca Markets (unified market data provider)
export {
  type AlpacaBar,
  AlpacaBarSchema,
  type AlpacaClientConfig,
  type AlpacaCorporateActionDividend,
  AlpacaCorporateActionDividendSchema,
  type AlpacaCorporateActionSplit,
  AlpacaCorporateActionSplitSchema,
  AlpacaMarketDataClient,
  type AlpacaOptionContract,
  AlpacaOptionContractSchema,
  type AlpacaOptionGreeks,
  AlpacaOptionGreeksSchema,
  type AlpacaOptionSnapshot,
  AlpacaOptionSnapshotSchema,
  type AlpacaQuote,
  AlpacaQuoteSchema,
  type AlpacaSnapshot,
  AlpacaSnapshotSchema,
  type AlpacaTimeframe,
  type AlpacaTrade,
  AlpacaTradeSchema,
  createAlpacaClientFromEnv,
  isAlpacaConfigured,
  type OptionContractParams,
} from "./alpaca";
// Alpaca WebSocket (real-time streaming)
export {
  AlpacaConnectionState,
  AlpacaWebSocketClient,
  type AlpacaWebSocketConfig,
  type AlpacaWsBarMessage,
  AlpacaWsBarMessageSchema,
  type AlpacaWsErrorMessage,
  AlpacaWsErrorMessageSchema,
  type AlpacaWsEvent,
  type AlpacaWsEventHandler,
  type AlpacaWsFeed,
  type AlpacaWsMarket,
  type AlpacaWsMessage,
  type AlpacaWsQuoteMessage,
  AlpacaWsQuoteMessageSchema,
  type AlpacaWsStatusMessage,
  AlpacaWsStatusMessageSchema,
  type AlpacaWsSubscriptionMessage,
  AlpacaWsSubscriptionMessageSchema,
  type AlpacaWsSuccessMessage,
  AlpacaWsSuccessMessageSchema,
  type AlpacaWsTradeMessage,
  AlpacaWsTradeMessageSchema,
  createAlpacaOptionsClientFromEnv,
  createAlpacaStocksClientFromEnv,
  createAlpacaWebSocketClientFromEnv,
} from "./alpaca-websocket";
// Alpha Vantage
export {
  ALPHA_VANTAGE_RATE_LIMITS,
  AlphaVantageClient,
  type AlphaVantageClientConfig,
  createAlphaVantageClientFromEnv,
  type EconomicDataPoint,
  EconomicDataPointSchema,
  type EconomicIndicatorResponse,
  EconomicIndicatorResponseSchema,
  type EconomicIndicatorType,
  type EconomicInterval,
  type FederalFundsRateResponse,
  FederalFundsRateResponseSchema,
  INDICATOR_METADATA,
  type IndicatorMetadata,
  type TreasuryMaturity,
  type TreasuryYieldResponse,
  TreasuryYieldResponseSchema,
} from "./alphavantage";
// FMP (Financial Modeling Prep)
export {
  type ConstituentChange,
  ConstituentChangeSchema,
  createFmpClientFromEnv,
  type EarningsEvent,
  EarningsEventSchema,
  type EarningsTranscript,
  EarningsTranscriptSchema,
  FMP_RATE_LIMITS,
  FmpClient,
  type FmpClientConfig,
  type IndexConstituent,
  IndexConstituentSchema,
  type PressRelease,
  PressReleaseSchema,
  type Quote,
  QuoteSchema,
  type ScreenerResult,
  ScreenerResultSchema,
  type SecFiling,
  SecFilingSchema,
  type SentimentRating,
  SentimentRatingSchema,
  type StockDividend,
  StockDividendSchema,
  type StockNews,
  StockNewsSchema,
  type StockSplit,
  StockSplitSchema,
  type SymbolChange,
  SymbolChangeSchema,
} from "./fmp";
