/**
 * Data Provider Clients
 *
 * API clients for market data providers.
 */

// Databento (execution-grade)
export {
  ConnectionState,
  createDatabentoClientFromEnv,
  DatabentoClient,
  type DatabentoClientConfig,
  type DatabentoDataset,
  type DatabentoEvent,
  type DatabentoMessage,
  type DatabentoSchema,
  type EventHandler,
  MBP10MessageSchema,
  type MBP10Message,
  OHLCVMessageSchema,
  type OHLCVMessage,
  QuoteMessageSchema,
  type QuoteMessage,
  type SubscriptionConfig,
  SymbolMappingMessageSchema,
  type SymbolMappingMessage,
  type SymbolType,
  SystemMessageSchema,
  type SystemMessage,
  TradeMessageSchema,
  type TradeMessage,
} from "./databento";

// Alpha Vantage
export {
  ALPHA_VANTAGE_RATE_LIMITS,
  AlphaVantageClient,
  type AlphaVantageClientConfig,
  createAlphaVantageClientFromEnv,
  type EconomicDataPoint,
  EconomicDataPointSchema,
  type EconomicIndicatorResponse,
  EconomicIndicatorResponseSchema,
  type EconomicInterval,
  type FederalFundsRateResponse,
  FederalFundsRateResponseSchema,
  type TreasuryMaturity,
  type TreasuryYieldResponse,
  TreasuryYieldResponseSchema,
} from "./alphavantage";
// FMP (Financial Modeling Prep)
export {
  type ConstituentChange,
  ConstituentChangeSchema,
  createFmpClientFromEnv,
  type EarningsEvent,
  EarningsEventSchema,
  type EarningsTranscript,
  EarningsTranscriptSchema,
  FMP_RATE_LIMITS,
  FmpClient,
  type FmpClientConfig,
  type IndexConstituent,
  IndexConstituentSchema,
  type PressRelease,
  PressReleaseSchema,
  type Quote,
  QuoteSchema,
  type ScreenerResult,
  ScreenerResultSchema,
  type SecFiling,
  SecFilingSchema,
  type SentimentRating,
  SentimentRatingSchema,
  type StockDividend,
  StockDividendSchema,
  type StockNews,
  StockNewsSchema,
  type StockSplit,
  StockSplitSchema,
  type SymbolChange,
  SymbolChangeSchema,
} from "./fmp";
// Polygon.io / Massive.com
export {
  type AggregateBar,
  AggregateBarSchema,
  type AggregatesResponse,
  AggregatesResponseSchema,
  createPolygonClientFromEnv,
  type Dividend,
  DividendSchema,
  type DividendsResponse,
  DividendsResponseSchema,
  type OptionChainResponse,
  OptionChainResponseSchema,
  type OptionContract,
  OptionContractSchema,
  POLYGON_RATE_LIMITS,
  PolygonClient,
  type PolygonClientConfig,
  type Snapshot,
  SnapshotSchema,
  type StockSplit as PolygonStockSplit,
  StockSplitSchema as PolygonStockSplitSchema,
  type StockSplitsResponse,
  StockSplitsResponseSchema,
  type TickersSnapshotResponse,
  TickersSnapshotResponseSchema,
  type Timespan,
} from "./polygon";
