// Cream Trading System - Execution Schema
// Messages for Rust execution engine communication

// @generated by protoc-gen-connect-es v0.13.0 with parameter "target=ts"
// @generated from file cream/v1/execution.proto (package cream.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CancelOrderRequest, CancelOrderResponse, CheckConstraintsRequest, CheckConstraintsResponse, GetAccountStateRequest, GetAccountStateResponse, GetOrderStateRequest, GetOrderStateResponse, GetPositionsRequest, GetPositionsResponse, StreamExecutionsRequest, StreamExecutionsResponse, SubmitOrderRequest, SubmitOrderResponse } from "./execution_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * Execution engine service
 *
 * @generated from service cream.v1.ExecutionService
 */
export const ExecutionService = {
  typeName: "cream.v1.ExecutionService",
  methods: {
    /**
     * Validate a decision plan against constraints
     *
     * @generated from rpc cream.v1.ExecutionService.CheckConstraints
     */
    checkConstraints: {
      name: "CheckConstraints",
      I: CheckConstraintsRequest,
      O: CheckConstraintsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Submit an order for execution
     *
     * @generated from rpc cream.v1.ExecutionService.SubmitOrder
     */
    submitOrder: {
      name: "SubmitOrder",
      I: SubmitOrderRequest,
      O: SubmitOrderResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Get order state by order ID
     *
     * @generated from rpc cream.v1.ExecutionService.GetOrderState
     */
    getOrderState: {
      name: "GetOrderState",
      I: GetOrderStateRequest,
      O: GetOrderStateResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Cancel an order
     *
     * @generated from rpc cream.v1.ExecutionService.CancelOrder
     */
    cancelOrder: {
      name: "CancelOrder",
      I: CancelOrderRequest,
      O: CancelOrderResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Stream order execution updates
     *
     * @generated from rpc cream.v1.ExecutionService.StreamExecutions
     */
    streamExecutions: {
      name: "StreamExecutions",
      I: StreamExecutionsRequest,
      O: StreamExecutionsResponse,
      kind: MethodKind.ServerStreaming,
    },
    /**
     * Get current account state
     *
     * @generated from rpc cream.v1.ExecutionService.GetAccountState
     */
    getAccountState: {
      name: "GetAccountState",
      I: GetAccountStateRequest,
      O: GetAccountStateResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Get current positions
     *
     * @generated from rpc cream.v1.ExecutionService.GetPositions
     */
    getPositions: {
      name: "GetPositions",
      I: GetPositionsRequest,
      O: GetPositionsResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

