// Cream Trading System - Market Snapshot Schema
// Real-time market data structures for the trading system
//
// NOTE: Using proto3 until Prost (Rust) supports Protobuf Editions.

// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts"
// @generated from file cream/v1/market_snapshot.proto (package cream.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { MethodKind } from "@bufbuild/protobuf";
import {
  GetOptionChainRequest,
  GetOptionChainResponse,
  GetSnapshotRequest,
  GetSnapshotResponse,
  SubscribeMarketDataRequest,
  SubscribeMarketDataResponse,
} from "./market_snapshot_pb.js";

/**
 * Market data streaming service
 *
 * @generated from service cream.v1.MarketDataService
 */
export const MarketDataService = {
  typeName: "cream.v1.MarketDataService",
  methods: {
    /**
     * Subscribe to real-time market data
     *
     * @generated from rpc cream.v1.MarketDataService.SubscribeMarketData
     */
    subscribeMarketData: {
      name: "SubscribeMarketData",
      I: SubscribeMarketDataRequest,
      O: SubscribeMarketDataResponse,
      kind: MethodKind.ServerStreaming,
    },
    /**
     * Get current snapshot for symbols
     *
     * @generated from rpc cream.v1.MarketDataService.GetSnapshot
     */
    getSnapshot: {
      name: "GetSnapshot",
      I: GetSnapshotRequest,
      O: GetSnapshotResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Get option chain for underlying
     *
     * @generated from rpc cream.v1.MarketDataService.GetOptionChain
     */
    getOptionChain: {
      name: "GetOptionChain",
      I: GetOptionChainRequest,
      O: GetOptionChainResponse,
      kind: MethodKind.Unary,
    },
  },
} as const;
